# This file was generated by GoReleaser. DO NOT EDIT.
cask "cclayer" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/cclayer"]
    end
  end

  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "617f282b4cb9b281d99411bd723b63e28ccabfeded0ab4613526d7affc608781"
      url "https://github.com/zhaojiannet/cclayer/releases/download/v#{version}/cclayer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc4d7e8a1bee3679c8f0b2931008659b87515ceefaa39c42740189f5738ba724"
      url "https://github.com/zhaojiannet/cclayer/releases/download/v#{version}/cclayer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "47879ac5721a66a365f7f87a00649620efd1f2165280554f7fd5f0fd7e720216"
      url "https://github.com/zhaojiannet/cclayer/releases/download/v#{version}/cclayer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1bfbafd87a62290f4ba783ead3f8a2222d7a84dc87ca4b47a5c3f717d09a5aee"
      url "https://github.com/zhaojiannet/cclayer/releases/download/v#{version}/cclayer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cclayer"
  desc "Sync Claude Code config across machines: CLAUDE.md, skills, hooks, settings.json, plugins and MCP servers, with per-team git identities and rules"
  homepage "https://github.com/zhaojiannet/cclayer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cclayer"

  # No zap stanza required
end
