# This file was generated by GoReleaser. DO NOT EDIT.
cask "cclayer" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/cclayer"]
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "6fedd767821aa7a56ac0d09042e83c1c154549ef431d159c8cf1b4f2f9c7b203"
      url "https://github.com/zhaojiannet/cclayer/releases/download/v#{version}/cclayer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "54bd721e8ed226b9e111da36eecc95c1e6c6f3ac115fe0c7762df49714260a96"
      url "https://github.com/zhaojiannet/cclayer/releases/download/v#{version}/cclayer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bf39b1ff8374ced39a004061ed94a3ba1b6ef5c09a3d2c6e965a34022e34df6c"
      url "https://github.com/zhaojiannet/cclayer/releases/download/v#{version}/cclayer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5eb7e0120310bb95f5fa8cc5b311463d2b15c523f81390d8f9b0007d0706a86e"
      url "https://github.com/zhaojiannet/cclayer/releases/download/v#{version}/cclayer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cclayer"
  desc "Sync Claude Code config across machines: CLAUDE.md, skills, hooks, settings.json, plugins and MCP servers, with per-team git identities and rules"
  homepage "https://github.com/zhaojiannet/cclayer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cclayer"

  # No zap stanza required
end
